services:
  api:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://postgres:postgres@db:5432/monapiclient
      - JWT_SECRET=superclejwt
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monapiclient
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  flyway:
    image: flyway/flyway:9
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
    command: -url=jdbc:postgresql://db:5432/monapiclient -user=postgres -password=postgres -baselineOnMigrate=true migrate


volumes:
  pgdata:
