# -------------------------------------
# Fichier : flyway.conf adapté à ta stack Docker Compose
# -------------------------------------

flyway.url=jdbc:postgresql://localhost:5432/monapiclient
flyway.user=postgres
flyway.password=postgres
flyway.locations=filesystem:./migrations
flyway.baselineOnMigrate=true
