services:
  api:
    build:
      context: .
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_URL=postgres://postgres:postgres@db:5432/monapiclient
      - ACCESS_TOKEN_SECRET=!ToB$%PraWh*8m3Bu2RYWqN
      - REFRESH_TOKEN_SECRET=Bi5@j^LcedeZ9RrH3eq
    volumes:
      - ./backend:/app
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monapiclient
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3000/api

  flyway:
    image: flyway/flyway:9
    depends_on:
      - db
    volumes:
      - ./migrations:/flyway/sql
    environment:
      FLYWAY_URL: jdbc:postgresql://db:5432/monapiclient
      FLYWAY_USER: postgres
      FLYWAY_PASSWORD: postgres
      FLYWAY_BASELINE_ON_MIGRATE: "true"
    command: migrate

volumes:
  pgdata:
